### PR TITLE
docs(ja):add docs developing/environment-variables and manifest/scheduled-job

### PR DESCRIPTION
**Pull request by G-F**
I translated below docs.
- developing/environment-variables
- manifest/scheduled-job

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by toricls — CHANGES_REQUESTED** [review]
Thanks for the PR @G-F! As we discussed offline the commit message should start with `docs(ja): ${your_message}`.
Could you do the following? 1) rebase your branch from the latest toricls/copilot-cli's `v1.5-docs-ja` branch, 2) change the commit message, 3) and force push your branch. Thanks!

**Comment by G-F** [comment]
Sorry, I fixed it.

**Review by toricls — CHANGES_REQUESTED** [review]
Could you also do this?
> 1) rebase your branch from the latest toricls/copilot-cli's `v1.5-docs-ja` branch

**Comment by G-F** [comment]
I'm sorry , I did rebase.

**Review by toricls — APPROVED** [review]
Thanks for your great work!

**Pull request merged**
